### ISSUE TITLE
Homepage has a lot of styles

### ISSUE THREAD

**Issue by mxstbr** [styled-components/styled-components-website#36]
For some reason the homepage ships a lot of styles (a few thousand lines) even though it should only serve the ones needed to render the homepage. Something's wrong, /cc @styled-components/core 🤔 

Maybe that's due to Next.js and how it renders?

h/t @threepointone @andrewingram

**Comment by mxstbr** [comment]
It has to be due to the fact how Next.js renders, does it render all the pages at once? That would explain why we inject all of the CSS, since that means all components are rendered. /cc @arunoda @rauchg

**Comment by philpl** [comment]
@mxstbr it is because we're not actually wrapping around the app. There's an open issue for this on next.js :)

https://github.com/zeit/next.js/issues/1751

**Comment by philpl** [comment]
This is resolved for now as I've added a vendored version of next with the fix mentioned above

**Comment by threepointone** [comment]
Looks good! I notice styled-components.com has a lot fewer styles now, so that's great. it still appears to be injecting every rule twice though?

**Comment by philpl** [comment]
@threepointone Wow! It indeed is. Wtf?

**Comment by mxstbr** [comment]
This is fixed, right?
